# Generated by Django 4.2 on 2022-11-01 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(default='01', max_length=35)),
                ('day_text', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(default='', max_length=35)),
                ('note_text', models.TextField(blank=True, default='')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 11, 1, 11, 11, 17, 411109, tzinfo=datetime.timezone.utc), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(default='', max_length=35)),
                ('month_text', models.TextField(blank=True, default='')),
                ('days', models.ManyToManyField(to='note_collection.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='attached_notes',
            field=models.ManyToManyField(to='note_collection.note'),
        ),
    ]
