# Generated by Django 4.2 on 2022-11-01 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 11, 11, 34, 251869, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
