# Generated by Django 4.2 on 2022-11-01 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_collection', '0002_alter_note_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='days_amount',
            field=models.IntegerField(default='1', max_length=31),
        ),
        migrations.AlterField(
            model_name='day',
            name='attached_notes',
            field=models.ManyToManyField(default=None, to='note_collection.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 11, 36, 54, 239530, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
