# Generated by Django 4.2 on 2022-11-01 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_collection', '0003_month_days_amount_alter_day_attached_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 11, 36, 58, 529733, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
