# Generated by Django 4.2 on 2022-11-01 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_collection', '0004_alter_note_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='days',
            field=models.ManyToManyField(default=None, to='note_collection.day'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 11, 37, 49, 30340, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
