# Generated by Django 4.2 on 2022-11-01 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_collection', '0007_alter_note_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 12, 5, 36, 359193, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
